name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile x86_64
        run: deno compile --output deno_raylib_demo-linuxX64 --allow-ffi --allow-env --allow-read --allow-write --allow-net --target x86_64-unknown-linux-gnu main.ts

      - name: Compile aarch64
        run: deno compile --output deno_raylib_demo-linuxAArch64 --allow-ffi --allow-env --allow-read --allow-write --allow-net --target aarch64-unknown-linux-gnu main.ts

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: Linux x64
          path: deno_raylib_demo-linuxX64

      - name: Upload aarch64
        uses: actions/upload-artifact@v4
        with:
          name: Linux aarch64
          path: deno_raylib_demo-linuxAArch64

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile x86_64
        run: deno compile --output deno_raylib_demo-macosX64 --allow-ffi --allow-env --allow-read --allow-write --allow-net --target x86_64-apple-darwin main.ts

      - name: Compile aarch64
        run: deno compile --output deno_raylib_demo-macosAArch64 --allow-ffi --allow-env --allow-read --allow-write --allow-net --target aarch64-apple-darwin main.ts

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: macOS x64
          path: deno_raylib_demo-macosX64

      - name: Upload aarch64
        uses: actions/upload-artifact@v4
        with:
          name: macOS aarch64
          path: deno_raylib_demo-macosAArch64

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile x86_64
        run: deno compile --output deno_raylib_demo-windowsX64 --allow-ffi --allow-env --allow-read --allow-write --allow-net --target x86_64-pc-windows-msvc main.ts

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64
          path: deno_raylib_demo-windowsX64
